In [1]:
import time
import glob
import cv2
import pprint
import sklearn
import numpy as np
import pandas as pd
import mediapipe as mp
import matplotlib.pyplot as plt

from sklearn.cluster import DBSCAN
# import hdbscan

%matplotlib inline

In [2]:
class FaceMeshDetector():

    def __init__(self, staticMode=False, maxFaces=2, minDetectionCon=0.5, minTrackCon=0.5):

        self.staticMode = staticMode
        self.maxFaces = maxFaces
        self.minDetectionCon = minDetectionCon
        self.minTrackCon = minTrackCon

        self.mpDraw = mp.solutions.drawing_utils
        self.mpFaceMesh = mp.solutions.face_mesh
        self.faceMesh = self.mpFaceMesh.FaceMesh(self.staticMode, self.maxFaces,
                                                 self.minDetectionCon, self.minTrackCon)
        self.drawSpec = self.mpDraw.DrawingSpec(thickness=1, circle_radius=2)

    def findFaceMesh(self, img, draw=True):
        
        self.imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        self.results = self.faceMesh.process(self.imgRGB)
        faces = []
        if self.results.multi_face_landmarks:
            for faceLms in self.results.multi_face_landmarks:
                if draw:
                    self.mpDraw.draw_landmarks(img, faceLms, self.mpFaceMesh.FACE_CONNECTIONS,
                                               self.drawSpec, self.drawSpec)
                face = []

                for id, lm in enumerate(faceLms.landmark):
                    
                    #                     print(lm)
                    
                    ih, iw, ic = self.imgRGB.shape
                    x = int(np.clip(lm.x, 0, 1)*(iw-1))
                    y = int(np.clip(lm.y, 0, 1)*(ih-1))
                    
#                     cv2.putText(img, str(id), (x, y), cv2.FONT_HERSHEY_PLAIN,
#                                1.3, (0, 255, 255), 2)

                    # print(id,x,y)

                    face.append(self.imgRGB[y, x, :])
                faces.append(face)
        return img, faces

In [17]:
# source_path = "data/test/"
source_path = "data/no_makeup/"
files_path = source_path + '*.jpeg'

image_files = [file_ for file_ in glob.glob(files_path)]

pprint.pprint(image_files)

['data/no_makeup/no_makeup0.jpeg',
 'data/no_makeup/no_makeup1.jpeg',
 'data/no_makeup/no_makeup1001.jpeg',
 'data/no_makeup/no_makeup1005.jpeg',
 'data/no_makeup/no_makeup1009.jpeg',
 'data/no_makeup/no_makeup101.jpeg',
 'data/no_makeup/no_makeup1018.jpeg',
 'data/no_makeup/no_makeup103.jpeg',
 'data/no_makeup/no_makeup1030.jpeg',
 'data/no_makeup/no_makeup1043.jpeg',
 'data/no_makeup/no_makeup1049.jpeg',
 'data/no_makeup/no_makeup105.jpeg',
 'data/no_makeup/no_makeup1054.jpeg',
 'data/no_makeup/no_makeup1056.jpeg',
 'data/no_makeup/no_makeup1069.jpeg',
 'data/no_makeup/no_makeup1074.jpeg',
 'data/no_makeup/no_makeup1081.jpeg',
 'data/no_makeup/no_makeup1083.jpeg',
 'data/no_makeup/no_makeup1091.jpeg',
 'data/no_makeup/no_makeup1095.jpeg',
 'data/no_makeup/no_makeup11.jpeg',
 'data/no_makeup/no_makeup1100.jpeg',
 'data/no_makeup/no_makeup1102.jpeg',
 'data/no_makeup/no_makeup1104.jpeg',
 'data/no_makeup/no_makeup1106.jpeg',
 'data/no_makeup/no_makeup1108.jpeg',
 'data/no_makeup/no_mak

In [4]:
plt.rcParams['figure.figsize'] = [48, 48]

# for colored printing
class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


In [5]:
# def get_face_land_values(image_files, FaceMeshDetector):

detector =  FaceMeshDetector(staticMode=True, maxFaces=2, minDetectionCon=0.5)

pTime = time.time()

median_rgbs = []
median_rgbs_idx = []
median_rgbs_info = []

for idx, file_ in enumerate(image_files):

    img_ = cv2.imread(file_)

    img_with_landmark, faces = detector.findFaceMesh(img_, draw=False)

#     plt.imshow(img_with_landmark)
#     plt.show()

    if len(faces) != 0:
        median_rgbs.append(np.median(faces[0], axis=0))
        median_rgbs_idx.append(idx)
        median_rgbs_info.append({'fullname': file_})
        print(f"{idx} file {file_} done ")
#          cv2.imwrite(source_path + "out/" + str(idx) + ".jpg", img_with_landmark, [int(cv2.IMWRITE_JPEG_QUALITY), 100])
        
    else:
        print(f"{bcolors.WARNING}Warning: {idx} face in file {file_} not found {bcolors.ENDC}")





# test exit
    # if idx//1 == 1:

    # break


# local fps 
    # cTime = time.time()
    # fps = 1 / (cTime - pTime)
    # pTime = cTime
    #  print(f'fps {fps:.1f}')


# global fps
cTime = time.time()
fps = len(image_files)//(cTime - pTime)
print(f'fps {fps:.1f}')

# np.median(faces[0], axis=0)


pprint.pprint(median_rgbs)


0 file data/no_makeup/no_makeup0.jpeg done 
1 file data/no_makeup/no_makeup1.jpeg done 
2 file data/no_makeup/no_makeup1001.jpeg done 
3 file data/no_makeup/no_makeup1005.jpeg done 
4 file data/no_makeup/no_makeup1009.jpeg done 
5 file data/no_makeup/no_makeup101.jpeg done 
6 file data/no_makeup/no_makeup1018.jpeg done 
7 file data/no_makeup/no_makeup103.jpeg done 
8 file data/no_makeup/no_makeup1030.jpeg done 
9 file data/no_makeup/no_makeup1043.jpeg done 
10 file data/no_makeup/no_makeup1049.jpeg done 
11 file data/no_makeup/no_makeup105.jpeg done 
12 file data/no_makeup/no_makeup1054.jpeg done 
13 file data/no_makeup/no_makeup1056.jpeg done 
14 file data/no_makeup/no_makeup1069.jpeg done 
15 file data/no_makeup/no_makeup1074.jpeg done 
16 file data/no_makeup/no_makeup1081.jpeg done 
17 file data/no_makeup/no_makeup1083.jpeg done 
18 file data/no_makeup/no_makeup1091.jpeg done 
19 file data/no_makeup/no_makeup1095.jpeg done 
20 file data/no_makeup/no_makeup11.jpeg done 
21 file data/

171 file data/no_makeup/no_makeup260.jpeg done 
172 file data/no_makeup/no_makeup262.jpeg done 
173 file data/no_makeup/no_makeup265.jpeg done 
174 file data/no_makeup/no_makeup268.jpeg done 
175 file data/no_makeup/no_makeup269.jpeg done 
176 file data/no_makeup/no_makeup270.jpeg done 
177 file data/no_makeup/no_makeup272.jpeg done 
178 file data/no_makeup/no_makeup273.jpeg done 
179 file data/no_makeup/no_makeup274.jpeg done 
180 file data/no_makeup/no_makeup275.jpeg done 
181 file data/no_makeup/no_makeup276.jpeg done 
182 file data/no_makeup/no_makeup282.jpeg done 
183 file data/no_makeup/no_makeup284.jpeg done 
184 file data/no_makeup/no_makeup286.jpeg done 
185 file data/no_makeup/no_makeup294.jpeg done 
186 file data/no_makeup/no_makeup295.jpeg done 
187 file data/no_makeup/no_makeup296.jpeg done 
188 file data/no_makeup/no_makeup297.jpeg done 
189 file data/no_makeup/no_makeup298.jpeg done 
190 file data/no_makeup/no_makeup301.jpeg done 
191 file data/no_makeup/no_makeup302.jpe

347 file data/no_makeup/no_makeup664.jpeg done 
348 file data/no_makeup/no_makeup665.jpeg done 
349 file data/no_makeup/no_makeup666.jpeg done 
350 file data/no_makeup/no_makeup667.jpeg done 
351 file data/no_makeup/no_makeup669.jpeg done 
352 file data/no_makeup/no_makeup67.jpeg done 
353 file data/no_makeup/no_makeup670.jpeg done 
354 file data/no_makeup/no_makeup672.jpeg done 
355 file data/no_makeup/no_makeup673.jpeg done 
356 file data/no_makeup/no_makeup676.jpeg done 
357 file data/no_makeup/no_makeup679.jpeg done 
358 file data/no_makeup/no_makeup681.jpeg done 
359 file data/no_makeup/no_makeup685.jpeg done 
360 file data/no_makeup/no_makeup686.jpeg done 
361 file data/no_makeup/no_makeup689.jpeg done 
362 file data/no_makeup/no_makeup690.jpeg done 
363 file data/no_makeup/no_makeup691.jpeg done 
364 file data/no_makeup/no_makeup692.jpeg done 
365 file data/no_makeup/no_makeup693.jpeg done 
366 file data/no_makeup/no_makeup695.jpeg done 
367 file data/no_makeup/no_makeup696.jpeg

In [6]:
gen_data = list(zip(median_rgbs_idx, median_rgbs[0], median_rgbs[1], median_rgbs[2], median_rgbs_info))
gen_data

[(0, 216.5, 192.0, 185.0, {'fullname': 'data/no_makeup/no_makeup0.jpeg'}),
 (1, 172.0, 136.0, 145.0, {'fullname': 'data/no_makeup/no_makeup1.jpeg'}),
 (2, 151.0, 120.0, 134.0, {'fullname': 'data/no_makeup/no_makeup1001.jpeg'})]

In [7]:
df = pd.DataFrame(gen_data,
               columns =['ID', 'MEDIAN_R', 'MEDIAN_G', 'MEDIAN_B', 'info'])

df.to_csv('data_face_colors.csv')
df

ID  MEDIAN_R  MEDIAN_G  MEDIAN_B  \
0   0     216.5     192.0     185.0   
1   1     172.0     136.0     145.0   
2   2     151.0     120.0     134.0   

                                                info  
0     {'fullname': 'data/no_makeup/no_makeup0.jpeg'}  
1     {'fullname': 'data/no_makeup/no_makeup1.jpeg'}  
2  {'fullname': 'data/no_makeup/no_makeup1001.jpeg'}

In [8]:
faces[0][0]

array([199, 137, 122], dtype=uint8)

In [9]:
median_rgbs = np.array(median_rgbs)

In [10]:
k_means = sklearn.cluster.KMeans(n_clusters=3, random_state=2)
k_means.fit_predict(median_rgbs)

k_means.labels_
k_means.cluster_centers_

array([[213.88721805, 168.52631579, 150.4887218 ],
       [182.60571429, 132.7       , 114.55428571],
       [148.96212121, 103.15530303,  87.48863636]])

In [11]:
best_epsilon = 5.2
for epsilon in range(1, 1000):
    dbscan = sklearn.cluster.DBSCAN(eps=epsilon/10, min_samples=len(image_files)//50)
    if max(dbscan.fit_predict(median_rgbs)) == 2:
        best_epsilon = epsilon/10
        print(best_epsilon)
        break
    

5.2


In [12]:
dbscan = sklearn.cluster.DBSCAN(eps=best_epsilon, min_samples=len(image_files)//50)
dbscan.fit_predict(median_rgbs)



array([-1, -1, -1,  0, -1, -1, -1,  0, -1, -1, -1, -1, -1, -1, -1,  1, -1,
       -1, -1, -1, -1, -1,  0, -1, -1,  1, -1, -1, -1,  0, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        2,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1,  0, -1,  2, -1, -1, -1, -1, -1, -1, -1,
       -1,  0, -1, -1, -1, -1,  1, -1,  0,  0, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1,  2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1,  0, -1, -1, -1, -1, -1,  2, -1,  2, -1, -1, -1, -1, -1, -1,
        0, -1, -1, -1,  0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1,
       -1,  1, -1, -1, -1,  2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,
       -1, -1, -1, -1, -1

In [13]:
max(dbscan.labels_)

2

In [14]:
median_rgbs[dbscan.fit_predict(median_rgbs)==1]

array([[197. , 146. , 127.5],
       [191.5, 145. , 126. ],
       [198.5, 145. , 128. ],
       [193. , 143. , 127. ],
       [198. , 147.5, 123. ],
       [196. , 147. , 132. ],
       [193. , 143. , 127. ],
       [194. , 149. , 128. ],
       [194. , 145. , 130. ]])